# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UjCGOZ7uhj7pqWEeE4Q5k49pRD0huK8D
"""

!pip install mrjob
from mrjob.job import MRJob

class MRViewbyDateCount(MRJob):
    
   
    def mapper(self, _, line):
        (business_id, date, review_id, stars, text, data_type, user_id, cool, useful, funny) = line.split(',')
        month = date[0:1]
        year = date[-4:-1]
        Year_Month = '%s - %s' % (year, month) 
        yield Year_Month, 1
    
    def reducer(self, key, value):
        yield Year_Month, sum(value)
        
if __name__ == '__main__':
    MRViewbyDateCount.run()