# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UjCGOZ7uhj7pqWEeE4Q5k49pRD0huK8D
"""

!pip install mrjob
from mrjob.job import MRJob

class MRWordRatingCount(MRJob):
    
    
    def mapper(self, _, line):
        (business_id, date, review_id, stars, text, data_type, user_id, cool, useful, funny) = line.split(',')
        yield "Cool", cool 
     
    def reducer(self, key, value):
        points = 0
        for i in value:
            if i != 0:
                points += i        
        yield "Cool", sum(points)/len(value)
            
if __name__ == '__main__':
    MRWordRatingCount.run()