# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CPGAR7UWjntzvLgazcHuzvzijVcUl0sx
"""

!pip install mrjob

from mrjob.job import MRJob

class MRWordFrequencyCount(MRJob):
    
   
    def mapper(self, _, line):
        (business_id, date, review_id, stars, text, data_type, user_id, cool, useful, funny) = line.split(',')
        NumWords = len(text.split()) 
        yield "Words", NumWords 
    
            
    def reducer(self, key, values):
        x, totalL, totalW = 0, 0, 0
        for x in values:
            totalW += x
            totalL += 1
        yield "Average", float(totalW)/(totalL)
        
if __name__ == '__main__':
    MRWordFrequencyCount.run()