# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LGd0EnXXCD_vcWtPj-_JM4yYhW_H2tlt
"""

import time
import socket
import requests
import csv
import json

HOST = '127.0.0.1'  # Standard loopback interface address (localhost)
PORT = 22223        # Port to listen on (non-privileged ports are > 1023) Most likely text[40:86]

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind((HOST, PORT))
    s.listen()
    conn, addr = s.accept()
    with conn:
        print('Connected by', addr)
        count = 0        
                                                            
        while True:
            data = requests.get('http://api.open-notify.org/iss-now.json').text 
                 
            if count <= 60:
                position = conn.sendall(str.encode(data +'\n'))
                count += 1
                time.sleep(60)
                with open("ISS.txt", "a", encoding="utf-8", newline="") as f:
                    f.write(data + '\n')          
                
            else:
                s.close()